### ISSUE TITLE
Emergency stop

### ISSUE THREAD

**Issue by AlexanderRBurke** [BinghamtonRover/RoverSystem#128]
The rover has a big red emergency stop button on it which will shutdown the whole rover system manually. This button can be difficult to press if the rover is going full speed away from us. So your task is to implement a similar emergency stop through a software message which will shutdown the rover system remotely.

**Comment by AlexanderRBurke** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Emergency stop](https://trello.com/c/djEFdQ38/12-emergency-stop)

**Comment by jlopez81** [comment]
[Emergency Stop.pdf](https://github.com/BinghamtonRover/RoverSystem/files/3686667/Emergency.Stop.pdf)
![Annotation 2019-09-23 170132](https://user-images.githubusercontent.com/55559862/66137694-7543a500-e5cb-11e9-8259-fe8323e3cef6.png)

[stop code.zip](https://github.com/BinghamtonRover/RoverSystem/files/3686672/stop.code.zip)

**Comment by jlopez81** [comment]
[Emergency Stop.pdf](https://github.com/BinghamtonRover/RoverSystem/files/3686674/Emergency.Stop.pdf)
[stop code.zip](https://github.com/BinghamtonRover/RoverSystem/files/3686675/stop.code.zip)

**Comment by layneson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Emergency stop](https://trello.com/c/4ws1yxWw/40-emergency-stop)
