### ISSUE TITLE
Waypoint Map/Editor

### ISSUE THREAD

**Issue by JordanLevin** [BinghamtonRover/RoverSystem#130]
Implement a map on the base station that shows where the rover is and the heading compared to current waypoints. Will also allow waypoints to be created and deleted.

**Comment by JordanLevin** [comment]
https://trello.com/c/cRKTbIzE

**Comment by AlexanderRBurke** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Waypoint Editor](https://trello.com/c/cRKTbIzE/14-waypoint-editor)
