### ISSUE TITLE
Network Statistics Collection/Display

### ISSUE THREAD

**Issue by layneson** [BinghamtonRover/RoverSystem#90]
Collect certain network statistics on the base station side, and display their real-time values on the GUI.

Calculate the "current" bandwidth and round trip time.

Bandwidth can be calculated by keeping track of how many bytes are sent and received over a set time interval, and divide that amount by the time interval. You may update the amount once per said time interval, or you may use a moving average if you are feeling fancy.

Round trip time (RTT) can be calculated by measuring the time it takes to send a packet over UDP and receive a response. Create a new packet type that can be sent at a fixed interval with the purpose of measuring RTT. Send it at a fixed interval! Once again, you can use a moving average if you want.

**Comment by ZeldaZach** [comment]
If time permits, display on the base station
